version: '3.3'

services:

  db:
    image: postgres:14.1
    hostname: '127.0.0.1'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: app